<?php

namespace kosssi\ExampleDoctrineEventsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SnakeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnakeRepository extends EntityRepository
{
}
